# Generated by Django 2.1.2 on 2018-10-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroonStudioAPI', '0003_auto_20181028_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('titleCateg',), 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='titleCateg',
        ),
    ]
