# Generated by Django 2.1.2 on 2018-10-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroonStudioAPI', '0004_auto_20181028_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='titleCateg',
            new_name='title',
        ),
    ]
