# Generated by Django 2.1.2 on 2018-10-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kroonStudioAPI', '0009_auto_20181029_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
