# Generated by Django 2.1.2 on 2018-10-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kroonStudioAPI', '0016_auto_20181029_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-updated_at__day',)},
        ),
    ]
