# Generated by Django 2.1.2 on 2018-10-30 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kroonStudioAPI', '0019_auto_20181029_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('cron_expression', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledReportGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedscheduledreport', to='kroonStudioAPI.ScheduledReport')),
            ],
        ),
        migrations.AddField(
            model_name='reportrecipient',
            name='scheduled_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportrecep', to='kroonStudioAPI.ScheduledReport'),
        ),
    ]
